name: Control Dockerfiles
on:
  push:
    paths:
      - 'Dockerfile*'
      - '.github/workflows/build-dockerfile.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Control that Dockerfile build
        run: |
          archs="aarch64 armv7hf"
          testtag=buildcheck
          for arch in $archs
          do
            printf "### Build Dockerfile.$arch\n"
            docker build -t $testtag:$arch -f Dockerfile.$arch .
          done

          for arch in $archs
          do
            printf "### Clean Dockerfile.$arch\n"
            docker image rm -f -t $testtag:$arch
          done

          printf "### All Dockerfiles build"
